import express from "express";
import authAdmin from "../middleware/authAdmin.js";
import { updateStatusController } from "../Controllers/adminControllers/onUser/updateStatusController.js";
import { getPendingController } from "../Controllers/adminControllers/onUser/getPendingController.js";
import { fetchUserController } from "../Controllers/adminControllers/onUser/fetchUserController.js";
import { body } from "express-validator";
import updateRoleController from "../Controllers/adminControllers/onUser/updateRoleController.js";
import { authSUDO } from "../middleware/authSUDO.js";
import { getAllUsers } from "../repo/getAllUsersQueries.js";
const adminUserRouter = express.Router();
adminUserRouter.patch("/:id/status",authAdmin,[body("status").isIn(["APPROVED", "REJECTED", "PENDING"])], updateStatusController);
adminUserRouter.get("/pending", authAdmin, getPendingController);
adminUserRouter.get("/:id", authAdmin, fetchUserController);
adminUserRouter.patch("/:id/role", authSUDO, [body("role").isIn(["SUDO", "ADMIN", "USER", "FATHER"])], updateRoleController);
adminUserRouter.get("/students",authAdmin,getAllUsers);
export default adminUserRouter;
