import express from 'express';
import authAdmin from '../middleware/authAdmin.ts';
import { createAttendanceController } from '../Controllers/adminControllers/attendanceControllers/createAttendanceController.ts';
import getAttendanceController from '../Controllers/adminControllers/attendanceControllers/getAttendanceController.ts';
const adminAttendanceRouter = express.Router();
adminAttendanceRouter.use(authAdmin);
// adminAttendanceRouter.get('/attendance', getAttendanceController);
adminAttendanceRouter.post('/', createAttendanceController);
adminAttendanceRouter.get('/:id',getAttendanceController );
export default adminAttendanceRouter;